export { default as Colors } from './ProgressColors.vue'
export { default as Indeterminate } from './ProgressIndeterminate.vue'
export { default as Percent } from './ProgressPercent.vue'
export { default as Sizes } from './ProgressSizes.vue'
export { default as Value } from './ProgressValue.vue'
