const variables = {
  '$button-background-color': '#4958f5',
  '$button-border-width': '2px',
  '$button-color': '#dbdbdb',
  '$danger': '#aa1e02',
  '$footer-background-color': 'rgba(0,0,0,0)',
  '$footer-padding': '10px',
  '$navbar-background-color': '#000',
  '$navbar-dropdown-arrow': 'white',
  '$navbar-height': '2.5rem',
  '$navbar-item-active-color': 'white',
  '$navbar-item-color': '#8b98cc',
  '$navbar-item-hover-background-color': 'rgba(255, 255, 255, 0%)',
  '$navbar-item-hover-color': '#6474b0',
  '$navbar-item-img-max-height': '4rem',
  '$primary': '#111',
  '$section-padding': '0.5rem 1.5rem',
  '$size-7': '0.875em',
  '$subtitle-family': 'MetrocleanExtrabold',
  '$title-family': 'MetrocleanExtrabold',
  '$turquoise-h': '317',
  '$turquoise-l': '35%',
  '$turquoise-s': '62%',
}

export default variables
